# Generated by Django 4.2.23 on 2025-08-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroom',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Main room image', null=True, upload_to='conference_rooms/'),
        ),
        migrations.AddField(
            model_name='conferenceroom',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Secondary room image', null=True, upload_to='conference_rooms/'),
        ),
        migrations.AddField(
            model_name='conferenceroom',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Additional room image', null=True, upload_to='conference_rooms/'),
        ),
        migrations.AddField(
            model_name='historicalconferenceroom',
            name='image_1',
            field=models.TextField(blank=True, help_text='Main room image', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalconferenceroom',
            name='image_2',
            field=models.TextField(blank=True, help_text='Secondary room image', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalconferenceroom',
            name='image_3',
            field=models.TextField(blank=True, help_text='Additional room image', max_length=100, null=True),
        ),
    ]
