# Generated by Django 4.2.23 on 2025-09-17 05:10

from django.db import migrations


def populate_existing_transactions(apps, schema_editor):
    """Create transaction records for existing paid orders"""
    Order = apps.get_model('restaurant', 'Order')
    Transaction = apps.get_model('restaurant', 'Transaction')
    
    # Get all paid orders
    paid_orders = Order.objects.filter(payment_status='paid')
    
    for order in paid_orders:
        # Check if transaction already exists
        if not Transaction.objects.filter(order=order).exists():
            Transaction.objects.create(
                transaction_type='order',
                order=order,
                customer_name=order.guest_name,
                table_number=order.table.table_number,
                amount=order.total_amount,
                payment_method='cash',  # Default to cash for existing orders
                created_by=order.created_by
            )


def reverse_populate_transactions(apps, schema_editor):
    """Remove transaction records created by this migration"""
    Transaction = apps.get_model('restaurant', 'Transaction')
    Transaction.objects.filter(transaction_type='order').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_transaction_historicaltransaction'),
    ]

    operations = [
        migrations.RunPython(populate_existing_transactions, reverse_populate_transactions),
    ]
