# Generated by Django 4.2.23 on 2025-09-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='booking',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('room', 'Room Booking'), ('restaurant', 'Restaurant'), ('conference', 'Conference'), ('booking_guest', 'Booking Guest'), ('other', 'Other Services')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('room', 'Room Booking'), ('restaurant', 'Restaurant'), ('conference', 'Conference'), ('booking_guest', 'Booking Guest'), ('other', 'Other Services')], max_length=20),
        ),
    ]
