# Generated by Django 4.2.23 on 2025-09-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurantinvoice_restaurantinvoiceitem_and_more'),
        ('billing', '0003_historicalinvoice_booking_invoice_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='restaurant.order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to='restaurant.order'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('room', 'Room Booking'), ('restaurant', 'Restaurant'), ('conference', 'Conference'), ('booking', 'Booking'), ('booking_guest', 'Booking Guest'), ('other', 'Other Services')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('room', 'Room Booking'), ('restaurant', 'Restaurant'), ('conference', 'Conference'), ('booking', 'Booking'), ('booking_guest', 'Booking Guest'), ('other', 'Other Services')], max_length=20),
        ),
    ]
