# Generated by Django 4.2.23 on 2025-09-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_historicalinvoice_order_invoice_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('custom', 'Custom Invoice'), ('gym', 'Gym'), ('swimming_pool', 'Swimming Pool'), ('booking', 'Booking Invoice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('custom', 'Custom Invoice'), ('gym', 'Gym'), ('swimming_pool', 'Swimming Pool'), ('booking', 'Booking Invoice')], max_length=20),
        ),
    ]
