# Generated by Django 4.2.23 on 2025-09-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_conferenceroom_image_1_conferenceroom_image_2_and_more'),
        ('billing', '0005_alter_historicalinvoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='conference_booking',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='conference.conferencebooking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='conference_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='conference.conferencebooking'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('custom', 'Custom Invoice'), ('gym', 'Gym'), ('swimming_pool', 'Swimming Pool'), ('booking', 'Booking Invoice'), ('conference', 'Conference Invoice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('custom', 'Custom Invoice'), ('gym', 'Gym'), ('swimming_pool', 'Swimming Pool'), ('booking', 'Booking Invoice'), ('conference', 'Conference Invoice')], max_length=20),
        ),
    ]
