# Generated by Django 4.2.23 on 2025-08-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_alter_guest_city_alter_guest_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='id_picture',
            field=models.ImageField(blank=True, help_text='Upload passport or identity document picture', null=True, upload_to='guest_id_pictures/'),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='id_picture',
            field=models.TextField(blank=True, help_text='Upload passport or identity document picture', max_length=100, null=True),
        ),
    ]
