# Generated by Django 4.2.23 on 2025-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guest_id_picture_historicalguest_id_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_type',
            field=models.CharField(choices=[('booking', 'Booking Guest'), ('gym', 'Gym Guest'), ('swimming', 'Swimming Pool Guest')], default='booking', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='guest_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='guest_type',
            field=models.CharField(choices=[('booking', 'Booking Guest'), ('gym', 'Gym Guest'), ('swimming', 'Swimming Pool Guest')], default='booking', max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalguest',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
