# Generated by Django 4.2.23 on 2025-09-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_guest_guest_source_guest_guest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
