# Generated by Django 4.2.23 on 2025-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('housekeeping', 'Housekeeping'), ('restaurant', 'Restaurant Staff'), ('conference', 'Conference Staff')], default='receptionist', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('housekeeping', 'Housekeeping'), ('restaurant', 'Restaurant Staff'), ('conference', 'Conference Staff')], default='receptionist', max_length=20),
        ),
    ]
